#encoding
#database : ssh 접속 - ubuntu@52.78.161.155
#database : mysql -h devops-rds.c7iudllookzy.ap-northeast-2.rds.amazonaws.com -u master -p
#static resources

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devops-rds-second.c7iudllookzy.ap-northeast-2.rds.amazonaws.com:3306/devops?useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: master
    password: ENC(ZC4mi7TZfj30yhG/KwbGSKoJQHEprP9v)
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
    
#server port
server:
  port: 8090
  
#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    password: devops
